name: news_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  envied: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  envied_generator: ^1.1.1


flutter:
  uses-material-design: true
