// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUm8BHL5iuLgRvOxWWQJiH6-bHmOjouI',
    appId: '1:597671681875:web:944ca1156e3313581fcba6',
    messagingSenderId: '597671681875',
    projectId: 'food-boxes-android',
    authDomain: 'food-boxes-android.firebaseapp.com',
    storageBucket: 'food-boxes-android.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBva7gPENC7bptCn8wuYTT7yzr2SGUQ5Zk',
    appId: '1:597671681875:android:fd435dd5a21c9de61fcba6',
    messagingSenderId: '597671681875',
    projectId: 'food-boxes-android',
    storageBucket: 'food-boxes-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrWqN3uSXy8EQPuyF05BJfMSD7IaHAeio',
    appId: '1:597671681875:ios:71f6ebb57d0833b61fcba6',
    messagingSenderId: '597671681875',
    projectId: 'food-boxes-android',
    storageBucket: 'food-boxes-android.appspot.com',
    iosClientId: '597671681875-4gi7red2stmbbk7jbj3jjuvgiclvj03e.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBoxes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrWqN3uSXy8EQPuyF05BJfMSD7IaHAeio',
    appId: '1:597671681875:ios:71f6ebb57d0833b61fcba6',
    messagingSenderId: '597671681875',
    projectId: 'food-boxes-android',
    storageBucket: 'food-boxes-android.appspot.com',
    iosClientId: '597671681875-4gi7red2stmbbk7jbj3jjuvgiclvj03e.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodBoxes',
  );
}
