include: package:flutter_lints/flutter.yaml

linter:
  rules:
      prefer_const_constructors: false
      prefer_const_declarations: false
      use_key_in_widget_constructors: false
      sort_child_properties_last: true
      prefer_final_in_for_each: true
      prefer_final_locals: true
      avoid_void_async: true
      unnecessary_parenthesis: true
      always_declare_return_types: true
      unawaited_futures: true
      only_throw_errors: true
      missing_whitespace_between_adjacent_strings: true